import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SolarSystem-GJ",
  description: "Generated by gaurav jangra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Drag hint */}
        <div
          id="statusEl"
          className="
            absolute
            left-2 top-2
            w-fit
            p-3
            bg-gray-800/80
            text-white
            rounded-xl
            text-sm md:text-base
            hidden
            z-50
          "
        >
          <h1>drag using left/right<br/>mouse button or touch</h1>
        </div>

        {/* ESC hint */}
        <div
          id="hint"
          className="
            absolute
            right-2 top-2
            w-fit
            p-3
            bg-gray-800/60
            text-white
            rounded-xl
            text-sm md:text-base
            hidden
            z-50
          "
        >
          <h1>Press ESC</h1>
        </div>

        {/* Planet Info */}
        <div
          id="planetInfo"
          className="
            absolute
            inset-x-4 md:inset-x-auto
            top-[20vh] md:ml-[35vw] 
            z-50
            mr-[10vw]
            max-w-[80vw] md:w-fit
            p-6 md:p-6
            text-white
            hidden
            bg-black/40
            rounded-2xl
            select-none
          "
        >
          <h2
            id="planetName"
            className="font-bold p-3 text-3xl md:text-5xl text-transparent bg-gradient-to-br
              from-blue-600 via-pink-600 to-sky-600 bg-clip-text"
          ></h2>
          <p
            id="planetIntro"
            className="font-bold p-3 text-xl md:text-2xl text-transparent bg-gradient-to-br
              from-yellow-600 via-sky-600 to-amber-600 bg-clip-text"
          ></p>
          <ul
            id="planetFacts"
            className="font-bold p-3 text-lg md:text-xl text-transparent bg-gradient-to-br
              from-gray-600 via-white to-gray-600 bg-clip-text"
          ></ul>
          <h6 className="text-gray-400 text-sm md:text-base">
            designed-by GAURAV JANGRA
          </h6>
        </div>

        {children}
      </body>
    </html>
  );
}
